exporter:
  collection_interval: "30s"
  otlp_endpoint: "localhost:4317"
  debug: true
nft_setup:
  protocol_family: "ip"
  table_name: "flowmon"
  chain_priority: -300
input_rules:
  - name: "Rest API SYN"
    #src_addr: "1.2.3.4"
    dst_port: 8080
    protocol: "tcp"
    flags: ["syn"]
output_rules:
  - name: "Rest API SYN+ACK"
    #dst_addr: "1.2.3.4"
    src_port: 8080
    protocol: "tcp"
    flags: ["syn", "ack"]
  
